### ISSUE TITLE
[NSFW] Pop-under ads on website: [phim18vnx.com]

### ISSUE THREAD

**Issue by nguyenminhkhmt** [abpvn/abpvn#506] opened 2023-01-05 07:41 UTC
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 13.0px 'Helvetica Neue'"><b>Ads description</b><br>
Website has pop-under ads when we play a video</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 13.0px 'Helvetica Neue'"><b>Step to reproduce</b></p>
<ol style="list-style-type: decimal">
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 13.0px 'Helvetica Neue'">Go to website</li>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 13.0px 'Helvetica Neue'">Click on any video thumbnails -&gt; Can’t click any video</li>
<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 13.0px 'Helvetica Neue'">Turn off ABP on Mobile app -&gt; Ads &amp; pop-under ads show. Can’t play video too.</li>
</ol>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 13.0px 'Helvetica Neue'">(We can reproduce it by refreshing a tab without clearing the browsing history)</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 13.0px 'Helvetica Neue'"><b>Website url</b></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 13.0px 'Helvetica Neue'; color: #dca10d"><a href="http://phim18vnx.com">phim18vnx.com</a></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 13.0px 'Helvetica Neue'; min-height: 15.0px"><br></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 13.0px 'Helvetica Neue'">With ABPVN Enabled</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 13.0px 'Helvetica Neue'; min-height: 15.0px"><br></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 20.0px 'Helvetica Neue'"><b>Environment</b></p>

Browser | Browser Version | Adblocker Version
-- | -- | --
Coc Coc (iOS) | 112.0.504 (or latest appstore ver) | SDK version: 0.11.1; Blocklist version: 202301050517
  |   |

**Comment by hoang-rio** [comment] 2023-01-05 08:01
Did CocCoc Browser Adblocker currently process rule $popup by block it open? That way make video can't play. Most of another Ad Blocker block popup allow it open then close and video can play normaly.

If you can confirm $popup rule processing like I said, I can not process this issue and you should close this issue.

I will check again when out of Business time.

Another Question for CocCoc Team: When CocCoc provider Adblocker Debug Method for me? A lot of issue only happend in CocCoc and can not reproduce in other browser so if have not Debug Method I can't do anything.

**Comment by nguyenminhkhmt** [comment] 2023-01-05 08:15
No, we only try to block CSS rules by 
```
phim18vnx.com##.preload-content
phim18vnx.com##.preload-pc
phim18hd.com,phim18hdz.com,phim18vnx.com##div[class="cash-fish"]```

I'll discuss with my team your question related to Adblocker Debug Method. Basically, we try to solve the issue with a Chrome app version first. And you can use Chrome debug tool :)

**Comment by hoang-rio** [comment] 2023-01-05 08:26
So domain is phim18vn.com or phim18vnx.com?

**Comment by nguyenminhkhmt** [comment] 2023-01-05 08:28
It should be phim18vnx.com now. site is redirected to a new one.

**Closed** 2023-01-06 12:57 UTC
Labels: Exist ads, NSFW

**Comment by nguyenminhkhmt** [comment] 2023-01-06 13:20
This issue is not solved yet. Please check step 2:
```2. Click on any video thumbnails -> Can’t click any video```
After enabling ABP, can't tap any video/link.

**Comment by hoang-rio** [comment] 2023-01-06 23:59
I checked in Chrome desktop and it working fine. Because no way to debug in CocCoc so I can not check it in CocCoc and I won't allow popup in all broweser only to fix this issue on CocCoc.

Please contact your team to find solution and give me filter that can fixed issue for you. You also try to add it in your browser specific filter list

**Comment by nguyenminhkhmt** [comment] 2023-01-11 06:38
@hoang-rio 
Here is the list we use in our browser:

https://browser.coccoc.com/js/ios_abp_custom_rules.txt
https://easylist-downloads.adblockplus.org/abpvn-minified.txt
https://easylist-downloads.adblockplus.org/easylist-minified.txt

**Comment by hoang-rio** [comment] 2023-01-11 09:11
Ok. I will check it in Chrome desktop with these filter list when I come back home

**Comment by hoang-rio** [comment] 2023-01-12 11:13
Check with these filter with ABP and it can play normaly. Also checked in Cốc Cốc Android app.

**Comment by nguyenminhkhmt** [comment] 2023-01-16 11:48
Still not working, please check with Coc Coc iOS mobile.
**Step 2: Click on any video thumbnails -> Can’t click any video**
![IMG_6954](https://user-images.githubusercontent.com/16470510/212671421-f2e9619c-440c-4388-9b20-e8d6c47ae216.PNG)

**Comment by hoang-rio** [comment] 2023-01-16 12:37
Same as #505 please don't comment when has debug method because I can't do anything without support tools

**Comment by hoang-rio** [comment] 2023-01-18 02:40
@nguyenminhkhmt Both ABPVN and CocCoc custom rule has bellow rule to hide modal ads in this site
```adblock
phim18vnx.com##.preload-pc
```

I don't know why CocCoc iOS skip or can't process this rule.
CocCoc Custom rule also has
```adblock
phim18vnx.com##.preload-content
```
this rule block content inside modal ads include close button. If CocCoc iOS can not process `##.preload-pc` rule you should remove `##.preload-content` rule because it allow use close modal ads with close button
